- 1: 
  - input:
    - 0
    - 0 
  - output:
    - 0
- 2: 
  - input:
    - 0
    - 1 
  - output:
    - 1
- 3: 
  - input:
    - 1
    - 0 
  - output:
    - 1
- 4: 
  - input:
    - 1
    - 1 
  - output:
    - 1
